package com.ngdata.jajc;

import java.util.ArrayList;
import java.util.Collection;

import org.jclouds.compute.domain.NodeMetadata;

import com.ngdata.jajc.providers.AbstractProvider;

public class ManifestBuilder {
	
	public static Iterable<String> createPuppetManifest(Iterable<NodeMetadata> instances)  {
		
		Collection<String> lines = new ArrayList<String>();
		lines.add("# This file was generated by the Java program, it contains the puppet manifest\n");
		lines.add("Exec  { path => [ '/bin' , '/sbin' , '/usr/bin' , '/usr/sbin' ] }");
		for ( NodeMetadata nm : instances) {
			lines.add("\n");
			lines.add("node '" + nm.getHostname() + "' {");
			StringBuilder sb = new StringBuilder(100);
			for ( String tag : AbstractProvider.extractRolesFromNode(nm)) {
				if (!"puppetmaster".equals(tag))
					sb.append(tag).append(",");
				else
					sb.append("mcollective::activemq::service,");
			}
			sb.deleteCharAt(sb.length()-1);
			lines.add("include " + sb);
			lines.add("}");
		}
		
		return lines;
	}
}
